services:
  - name: mcq-generator-backend
    type: web
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader punkt stopwords wordnet
      pip install gevent
    startCommand: gunicorn --worker-class=gevent --workers=1 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    plan: free